export const GAMES = [
    // Game 1
    [
        { shapeId: 3, offset: [0, 0], mutable: true },
        { shapeId: 4, offset: [0, 0], mutable: true },
        { shapeId: 6, offset: [0, 0], mutable: true },
        { shapeId: 10, offset: [0, 0], mutable: true },
        { shapeId: 12, offset: [0, 0], mutable: true },
        { shapeId: 13, offset: [0, 0], mutable: true },
        { shapeId: 13, offset: [0, 0], mutable: true },
        { shapeId: 27, offset: [0, 0], mutable: true },
        { shapeId: 0, offset: [0, 0], mutable: false },
        { shapeId: 0, offset: [9, 0], mutable: false },
        { shapeId: 3, offset: [1, 1], mutable: false },
        { shapeId: 12, offset: [5, 1], mutable: false, flip: true, rotate: 1 },
    ],
    // Game 2
    [
        { shapeId: 2, offset: [0, 0], mutable: true },
        { shapeId: 7, offset: [0, 0], mutable: true },
        { shapeId: 11, offset: [0, 0], mutable: true },
        { shapeId: 16, offset: [0, 0], mutable: true },
        { shapeId: 22, offset: [0, 0], mutable: true },
        { shapeId: 24, offset: [0, 0], mutable: true },
        { shapeId: 27, offset: [0, 0], mutable: true },
        { shapeId: 30, offset: [0, 0], mutable: true },
        { shapeId: 0, offset: [0, 0], mutable: false },
        { shapeId: 0, offset: [9, 0], mutable: false },
        { shapeId: 11, offset: [6, 0], mutable: false, rotate: 1 },
        { shapeId: 27, offset: [6, 2], mutable: false, flip: true, rotate: 2 },
    ],
    // Game 3
    [
        { shapeId: 2, offset: [0, 0], mutable: true },
        { shapeId: 5, offset: [0, 0], mutable: true },
        { shapeId: 6, offset: [0, 0], mutable: true },
        { shapeId: 7, offset: [0, 0], mutable: true },
        { shapeId: 10, offset: [0, 0], mutable: true },
        { shapeId: 12, offset: [0, 0], mutable: true },
        { shapeId: 24, offset: [0, 0], mutable: true },
        { shapeId: 25, offset: [0, 0], mutable: true },
        { shapeId: 0, offset: [0, 0], mutable: false },
        { shapeId: 0, offset: [9, 0], mutable: false },
        { shapeId: 7, offset: [7, 0], mutable: false, flip: true, rotate: 2 },
        { shapeId: 10, offset: [3, 2], mutable: false },
    ],
    // Game 4
    [
        { shapeId: 1, offset: [0, 0], mutable: true },
        { shapeId: 3, offset: [0, 0], mutable: true },
        { shapeId: 7, offset: [0, 0], mutable: true },
        { shapeId: 7, offset: [0, 0], mutable: true },
        { shapeId: 14, offset: [0, 0], mutable: true },
        { shapeId: 15, offset: [0, 0], mutable: true },
        { shapeId: 21, offset: [0, 0], mutable: true },
        { shapeId: 30, offset: [0, 0], mutable: true },
        { shapeId: 0, offset: [0, 0], mutable: false },
        { shapeId: 0, offset: [9, 0], mutable: false },
        { shapeId: 1, offset: [1, 0], mutable: false },
        { shapeId: 30, offset: [6, 3], mutable: false },
    ],
    // Game 5
    [
        { shapeId: 2, offset: [0, 0], mutable: true },
        { shapeId: 9, offset: [0, 0], mutable: true },
        { shapeId: 10, offset: [0, 0], mutable: true },
        { shapeId: 12, offset: [0, 0], mutable: true },
        { shapeId: 13, offset: [0, 0], mutable: true },
        { shapeId: 16, offset: [0, 0], mutable: true },
        { shapeId: 25, offset: [0, 0], mutable: true },
        { shapeId: 30, offset: [0, 0], mutable: true },
        { shapeId: 0, offset: [0, 0], mutable: false },
        { shapeId: 0, offset: [9, 0], mutable: false },
        { shapeId: 10, offset: [5, 0], mutable: false, rotate: 3},
        { shapeId: 30, offset: [1, 0], mutable: false, flip: true, rotate: 2 },
    ],
    // Game 6
    [
        { shapeId: 6, offset: [0, 0], mutable: true },
        { shapeId: 7, offset: [0, 0], mutable: true },
        { shapeId: 7, offset: [0, 0], mutable: true },
        { shapeId: 11, offset: [0, 0], mutable: true },
        { shapeId: 14, offset: [0, 0], mutable: true },
        { shapeId: 16, offset: [0, 0], mutable: true },
        { shapeId: 17, offset: [0, 0], mutable: true },
        { shapeId: 20, offset: [0, 0], mutable: true },
        { shapeId: 0, offset: [0, 0], mutable: false },
        { shapeId: 0, offset: [9, 0], mutable: false },
        { shapeId: 7, offset: [7, 2], mutable: false },
        { shapeId: 16, offset: [1, 0], mutable: false, rotate: 1 },
    ],
    // Game 7
    [
        { shapeId: 1, offset: [0, 0], mutable: true },
        { shapeId: 4, offset: [0, 0], mutable: true },
        { shapeId: 13, offset: [0, 0], mutable: true },
        { shapeId: 13, offset: [0, 0], mutable: true },
        { shapeId: 19, offset: [0, 0], mutable: true },
        { shapeId: 20, offset: [0, 0], mutable: true },
        { shapeId: 25, offset: [0, 0], mutable: true },
        { shapeId: 27, offset: [0, 0], mutable: true },
        { shapeId: 0, offset: [0, 0], mutable: false },
        { shapeId: 0, offset: [9, 0], mutable: false },
        { shapeId: 1, offset: [7, 0], mutable: false, flip: true },
        { shapeId: 25, offset: [1, 0], mutable: false, rotate: 1 },
    ],
    // Game 8
    [
        { shapeId: 3, offset: [0, 0], mutable: true },
        { shapeId: 5, offset: [0, 0], mutable: true },
        { shapeId: 7, offset: [0, 0], mutable: true },
        { shapeId: 10, offset: [0, 0], mutable: true },
        { shapeId: 11, offset: [0, 0], mutable: true },
        { shapeId: 20, offset: [0, 0], mutable: true },
        { shapeId: 22, offset: [0, 0], mutable: true },
        { shapeId: 27, offset: [0, 0], mutable: true },
        { shapeId: 0, offset: [0, 0], mutable: false },
        { shapeId: 0, offset: [9, 0], mutable: false },
        { shapeId: 3, offset: [7, 0], mutable: false, flip: true },
        { shapeId: 22, offset: [4, 0], mutable: false, flip: true, rotate: 1 },
    ],
    // Game 9
    [
        { shapeId: 1, offset: [0, 0], mutable: true },
        { shapeId: 9, offset: [0, 0], mutable: true },
        { shapeId: 15, offset: [0, 0], mutable: true },
        { shapeId: 19, offset: [0, 0], mutable: true },
        { shapeId: 20, offset: [0, 0], mutable: true },
        { shapeId: 25, offset: [0, 0], mutable: true },
        { shapeId: 30, offset: [0, 0], mutable: true },
        { shapeId: 33, offset: [0, 0], mutable: true },
        { shapeId: 0, offset: [0, 0], mutable: false },
        { shapeId: 0, offset: [9, 0], mutable: false },
        { shapeId: 33, offset: [4, 2], mutable: false },
    ],
    // Game 10
    [
        { shapeId: 1, offset: [0, 0], mutable: true },
        { shapeId: 14, offset: [0, 0], mutable: true },
        { shapeId: 20, offset: [0, 0], mutable: true },
        { shapeId: 22, offset: [0, 0], mutable: true },
        { shapeId: 25, offset: [0, 0], mutable: true },
        { shapeId: 27, offset: [0, 0], mutable: true },
        { shapeId: 31, offset: [0, 0], mutable: true },
        { shapeId: 34, offset: [0, 0], mutable: true },
        { shapeId: 0, offset: [0, 0], mutable: false },
        { shapeId: 0, offset: [9, 0], mutable: false },
        { shapeId: 27, offset: [5, 0], mutable: false, rotate: 3 },
    ],
    // Game 11
    [
        { shapeId: 2, offset: [0, 0], mutable: true },
        { shapeId: 10, offset: [0, 0], mutable: true },
        { shapeId: 11, offset: [0, 0], mutable: true },
        { shapeId: 14, offset: [0, 0], mutable: true },
        { shapeId: 19, offset: [0, 0], mutable: true },
        { shapeId: 21, offset: [0, 0], mutable: true },
        { shapeId: 25, offset: [0, 0], mutable: true },
        { shapeId: 27, offset: [0, 0], mutable: true },
        { shapeId: 0, offset: [0, 0], mutable: false },
        { shapeId: 0, offset: [9, 0], mutable: false },
        { shapeId: 21, offset: [4, 2], mutable: false },
    ],
    // Game 12
    [
        { shapeId: 1, offset: [0, 0], mutable: true },
        { shapeId: 2, offset: [0, 0], mutable: true },
        { shapeId: 6, offset: [0, 0], mutable: true },
        { shapeId: 14, offset: [0, 0], mutable: true },
        { shapeId: 15, offset: [0, 0], mutable: true },
        { shapeId: 20, offset: [0, 0], mutable: true },
        { shapeId: 21, offset: [0, 0], mutable: true },
        { shapeId: 29, offset: [0, 0], mutable: true },
        { shapeId: 0, offset: [0, 0], mutable: false },
        { shapeId: 0, offset: [9, 0], mutable: false },
        { shapeId: 15, offset: [4, 2], mutable: false, rotate: 1 },
    ],
    // Game 13
    [
        { shapeId: 10, offset: [0, 0], mutable: true },
        { shapeId: 13, offset: [0, 0], mutable: true },
        { shapeId: 14, offset: [0, 0], mutable: true },
        { shapeId: 15, offset: [0, 0], mutable: true },
        { shapeId: 16, offset: [0, 0], mutable: true },
        { shapeId: 23, offset: [0, 0], mutable: true },
        { shapeId: 25, offset: [0, 0], mutable: true },
        { shapeId: 32, offset: [0, 0], mutable: true },
        { shapeId: 0, offset: [0, 0], mutable: false },
        { shapeId: 0, offset: [9, 0], mutable: false },
        { shapeId: 23, offset: [4, 1], mutable: false, flip: true },
    ],
    // Game 14
    [
        { shapeId: 3, offset: [0, 0], mutable: true },
        { shapeId: 7, offset: [0, 0], mutable: true },
        { shapeId: 11, offset: [0, 0], mutable: true },
        { shapeId: 18, offset: [0, 0], mutable: true },
        { shapeId: 21, offset: [0, 0], mutable: true },
        { shapeId: 27, offset: [0, 0], mutable: true },
        { shapeId: 29, offset: [0, 0], mutable: true },
        { shapeId: 30, offset: [0, 0], mutable: true },
        { shapeId: 0, offset: [0, 0], mutable: false },
        { shapeId: 0, offset: [9, 0], mutable: false },
        { shapeId: 11, offset: [3, 1], mutable: false, rotate: 1 },
    ],
    // Game 15
    [
        { shapeId: 1, offset: [0, 0], mutable: true },
        { shapeId: 4, offset: [0, 0], mutable: true },
        { shapeId: 7, offset: [0, 0], mutable: true },
        { shapeId: 11, offset: [0, 0], mutable: true },
        { shapeId: 17, offset: [0, 0], mutable: true },
        { shapeId: 20, offset: [0, 0], mutable: true },
        { shapeId: 29, offset: [0, 0], mutable: true },
        { shapeId: 30, offset: [0, 0], mutable: true },
        { shapeId: 0, offset: [0, 0], mutable: false },
        { shapeId: 0, offset: [9, 0], mutable: false },
    ],
    // Game 16
    [
        { shapeId: 1, offset: [0, 0], mutable: true },
        { shapeId: 6, offset: [0, 0], mutable: true },
        { shapeId: 11, offset: [0, 0], mutable: true },
        { shapeId: 13, offset: [0, 0], mutable: true },
        { shapeId: 13, offset: [0, 0], mutable: true },
        { shapeId: 25, offset: [0, 0], mutable: true },
        { shapeId: 30, offset: [0, 0], mutable: true },
        { shapeId: 34, offset: [0, 0], mutable: true },
        { shapeId: 0, offset: [0, 0], mutable: false },
        { shapeId: 0, offset: [9, 0], mutable: false },
    ],
    // Game 17
    [
        { shapeId: 5, offset: [0, 0], mutable: true },
        { shapeId: 8, offset: [0, 0], mutable: true },
        { shapeId: 10, offset: [0, 0], mutable: true },
        { shapeId: 11, offset: [0, 0], mutable: true },
        { shapeId: 12, offset: [0, 0], mutable: true },
        { shapeId: 19, offset: [0, 0], mutable: true },
        { shapeId: 24, offset: [0, 0], mutable: true },
        { shapeId: 24, offset: [0, 0], mutable: true },
        { shapeId: 25, offset: [0, 0], mutable: true },
        { shapeId: 0, offset: [0, 0], mutable: false },
        { shapeId: 24, offset: [1, 0], mutable: false },
        { shapeId: 25, offset: [7, 0], mutable: false, rotate: 2 },
        { shapeId: 10, offset: [6, 3], mutable: false, flip, rotate: 3 },
    ],
    // Game 18
    [
        { shapeId: 2, offset: [0, 0], mutable: true },
        { shapeId: 3, offset: [0, 0], mutable: true },
        { shapeId: 7, offset: [0, 0], mutable: true },
        { shapeId: 7, offset: [0, 0], mutable: true },
        { shapeId: 13, offset: [0, 0], mutable: true },
        { shapeId: 14, offset: [0, 0], mutable: true },
        { shapeId: 22, offset: [0, 0], mutable: true },
        { shapeId: 29, offset: [0, 0], mutable: true },
        { shapeId: 30, offset: [0, 0], mutable: true },
        { shapeId: 0, offset: [0, 0], mutable: false },
        { shapeId: 14, offset: [1, 2], mutable: false },
        { shapeId: 2, offset: [2, 4], mutable: false, rotate: 1 },
        { shapeId: 22, offset: [8, 2], mutable: false },
    ],
    // Game 19
    [
        { shapeId: 2, offset: [0, 0], mutable: true },
        { shapeId: 5, offset: [0, 0], mutable: true },
        { shapeId: 12, offset: [0, 0], mutable: true },
        { shapeId: 13, offset: [0, 0], mutable: true },
        { shapeId: 14, offset: [0, 0], mutable: true },
        { shapeId: 18, offset: [0, 0], mutable: true },
        { shapeId: 23, offset: [0, 0], mutable: true },
        { shapeId: 24, offset: [0, 0], mutable: true },
        { shapeId: 25, offset: [0, 0], mutable: true },
        { shapeId: 0, offset: [0, 0], mutable: false },
        { shapeId: 24, offset: [7, 0], mutable: false, rotate: 1 },
        { shapeId: 25, offset: [7, 3], mutable: false, flip: true },
        { shapeId: 12, offset: [6, 1], mutable: false, rotate: 2 },
    ],
    // Game 20
    [
        { shapeId: 0, offset: [0, 0], mutable: true },
        { shapeId: 9, offset: [0, 0], mutable: true },
        { shapeId: 10, offset: [0, 0], mutable: true },
        { shapeId: 15, offset: [0, 0], mutable: true },
        { shapeId: 18, offset: [0, 0], mutable: true },
        { shapeId: 23, offset: [0, 0], mutable: true },
        { shapeId: 24, offset: [0, 0], mutable: true },
        { shapeId: 24, offset: [0, 0], mutable: true },
        { shapeId: 28, offset: [0, 0], mutable: true },
        { shapeId: 0, offset: [0, 0], mutable: false },
        { shapeId: 10, offset: [1, 0], mutable: false, rotate: 2 },
        { shapeId: 0, offset: [1, 5], mutable: false, rotate: 1 },
        { shapeId: 28, offset: [6, 4], mutable: false, flip: true, rotate: 3 },
    ],
    // Game 21
    [
        { shapeId: 1, offset: [0, 0], mutable: true },
        { shapeId: 6, offset: [0, 0], mutable: true },
        { shapeId: 7, offset: [0, 0], mutable: true },
        { shapeId: 20, offset: [0, 0], mutable: true },
        { shapeId: 22, offset: [0, 0], mutable: true },
        { shapeId: 26, offset: [0, 0], mutable: true },
        { shapeId: 29, offset: [0, 0], mutable: true },
        { shapeId: 30, offset: [0, 0], mutable: true },
        { shapeId: 34, offset: [0, 0], mutable: true },
        { shapeId: 0, offset: [0, 0], mutable: false },
        { shapeId: 26, offset: [1, 0], mutable: false, flip: true, rotate: 3 },
        { shapeId: 34, offset: [5, 2], mutable: false, flip: true, rotate: 3 },
    ],
    // Game 22
    [
        { shapeId: 1, offset: [0, 0], mutable: true },
        { shapeId: 7, offset: [0, 0], mutable: true },
        { shapeId: 10, offset: [0, 0], mutable: true },
        { shapeId: 11, offset: [0, 0], mutable: true },
        { shapeId: 14, offset: [0, 0], mutable: true },
        { shapeId: 16, offset: [0, 0], mutable: true },
        { shapeId: 25, offset: [0, 0], mutable: true },
        { shapeId: 27, offset: [0, 0], mutable: true },
        { shapeId: 30, offset: [0, 0], mutable: true },
        { shapeId: 0, offset: [0, 0], mutable: false },
        { shapeId: 10, offset: [1, 3], mutable: false, rotate: 1 },
        { shapeId: 7, offset: [8, 0], mutable: false, flip: true, rotate: 2 },
    ],
    // Game 23
    [
        { shapeId: 0, offset: [0, 0], mutable: true },
        { shapeId: 4, offset: [0, 0], mutable: true },
        { shapeId: 7, offset: [0, 0], mutable: true },
        { shapeId: 7, offset: [0, 0], mutable: true },
        { shapeId: 15, offset: [0, 0], mutable: true },
        { shapeId: 21, offset: [0, 0], mutable: true },
        { shapeId: 26, offset: [0, 0], mutable: true },
        { shapeId: 28, offset: [0, 0], mutable: true },
        { shapeId: 30, offset: [0, 0], mutable: true },
        { shapeId: 0, offset: [0, 0], mutable: false },
        { shapeId: 0, offset: [2, 5], mutable: false, rotate: 1 },
        { shapeId: 21, offset: [4, 2], mutable: false, rotate: 3 },
    ],
    // Game 24
    [
        { shapeId: 1, offset: [0, 0], mutable: true },
        { shapeId: 7, offset: [0, 0], mutable: true },
        { shapeId: 9, offset: [0, 0], mutable: true },
        { shapeId: 10, offset: [0, 0], mutable: true },
        { shapeId: 14, offset: [0, 0], mutable: true },
        { shapeId: 17, offset: [0, 0], mutable: true },
        { shapeId: 25, offset: [0, 0], mutable: true },
        { shapeId: 28, offset: [0, 0], mutable: true },
        { shapeId: 32, offset: [0, 0], mutable: true },
        { shapeId: 0, offset: [0, 0], mutable: false },
        { shapeId: 10, offset: [1, 3], mutable: false, rotate: 1 },
        { shapeId: 32, offset: [5, 2], mutable: false },
    ],
    // Game 25
    [
        { shapeId: 1, offset: [0, 0], mutable: true },
        { shapeId: 2, offset: [0, 0], mutable: true },
        { shapeId: 3, offset: [0, 0], mutable: true },
        { shapeId: 7, offset: [0, 0], mutable: true },
        { shapeId: 15, offset: [0, 0], mutable: true },
        { shapeId: 21, offset: [0, 0], mutable: true },
        { shapeId: 25, offset: [0, 0], mutable: true },
        { shapeId: 27, offset: [0, 0], mutable: true },
        { shapeId: 28, offset: [0, 0], mutable: true },
        { shapeId: 0, offset: [0, 0], mutable: false },
        { shapeId: 15, offset: [6, 1], mutable: false },
        { shapeId: 21, offset: [2, 1], mutable: false, rotate: 2 },
    ],
    // Game 26
    [
        { shapeId: 2, offset: [0, 0], mutable: true },
        { shapeId: 4, offset: [0, 0], mutable: true },
        { shapeId: 7, offset: [0, 0], mutable: true },
        { shapeId: 7, offset: [0, 0], mutable: true },
        { shapeId: 11, offset: [0, 0], mutable: true },
        { shapeId: 24, offset: [0, 0], mutable: true },
        { shapeId: 26, offset: [0, 0], mutable: true },
        { shapeId: 28, offset: [0, 0], mutable: true },
        { shapeId: 34, offset: [0, 0], mutable: true },
        { shapeId: 0, offset: [0, 0], mutable: false },
        { shapeId: 7, offset: [1, 2], mutable: false, rotate: 2 },
        { shapeId: 28, offset: [2, 4], mutable: false, rotate: 1 },
    ],
    // Game 27
    [
        { shapeId: 0, offset: [0, 0], mutable: true },
        { shapeId: 3, offset: [0, 0], mutable: true },
        { shapeId: 9, offset: [0, 0], mutable: true },
        { shapeId: 10, offset: [0, 0], mutable: true },
        { shapeId: 11, offset: [0, 0], mutable: true },
        { shapeId: 12, offset: [0, 0], mutable: true },
        { shapeId: 25, offset: [0, 0], mutable: true },
        { shapeId: 26, offset: [0, 0], mutable: true },
        { shapeId: 28, offset: [0, 0], mutable: true },
        { shapeId: 0, offset: [0, 0], mutable: false },
        { shapeId: 26, offset: [4, 1], mutable: false, flip: true, rotate: 3 },
    ],
    // Game 28
    [
        { shapeId: 0, offset: [0, 0], mutable: true },
        { shapeId: 5, offset: [0, 0], mutable: true },
        { shapeId: 7, offset: [0, 0], mutable: true },
        { shapeId: 9, offset: [0, 0], mutable: true },
        { shapeId: 10, offset: [0, 0], mutable: true },
        { shapeId: 11, offset: [0, 0], mutable: true },
        { shapeId: 14, offset: [0, 0], mutable: true },
        { shapeId: 16, offset: [0, 0], mutable: true },
        { shapeId: 18, offset: [0, 0], mutable: true },
        { shapeId: 0, offset: [0, 0], mutable: false },
        { shapeId: 11, offset: [4, 2], mutable: false, rotate: 1 },
    ],
    // Game 29
    [
        { shapeId: 1, offset: [0, 0], mutable: true },
        { shapeId: 2, offset: [0, 0], mutable: true },
        { shapeId: 4, offset: [0, 0], mutable: true },
        { shapeId: 7, offset: [0, 0], mutable: true },
        { shapeId: 12, offset: [0, 0], mutable: true },
        { shapeId: 16, offset: [0, 0], mutable: true },
        { shapeId: 21, offset: [0, 0], mutable: true },
        { shapeId: 28, offset: [0, 0], mutable: true },
        { shapeId: 29, offset: [0, 0], mutable: true },
        { shapeId: 0, offset: [0, 0], mutable: false },
        { shapeId: 4, offset: [6, 2], mutable: false, flip: true, rotate: 3 },
    ],
    // Game 30
    [
        { shapeId: 1, offset: [0, 0], mutable: true },
        { shapeId: 2, offset: [0, 0], mutable: true },
        { shapeId: 4, offset: [0, 0], mutable: true },
        { shapeId: 5, offset: [0, 0], mutable: true },
        { shapeId: 6, offset: [0, 0], mutable: true },
        { shapeId: 9, offset: [0, 0], mutable: true },
        { shapeId: 12, offset: [0, 0], mutable: true },
        { shapeId: 13, offset: [0, 0], mutable: true },
        { shapeId: 13, offset: [0, 0], mutable: true },
        { shapeId: 0, offset: [0, 0], mutable: false },
        { shapeId: 13, offset: [3, 2], mutable: false },
    ]
]